name: StackStorage_core
main: ree_jp\stackStorage\StackStoragePlugin
api : 3.0.0
version: 0.0.7
author: Ree-jp
permissions:
  stackstorage.command:
    my:
     default: true
    user:
     default: op
